"""Fetch per-item stat metadata (primary/secondary stat types) for every
item referenced in Where2Go/Core/Sources.lua, from the Battle.net Game
Data API. Stages output at tools/data-prep/scratch/ItemStats.lua.new and
prints a diff against the committed Where2Go/Core/ItemStats.lua for
review -- never writes that file directly.

Usage:
    $env:BLIZZARD_CLIENT_ID="<your id>"; $env:BLIZZARD_CLIENT_SECRET="<your secret>"; python tools/data-prep/generate_item_stats.py

See docs/SEASON_CHECKLIST.md for the full season-changeover procedure.
"""

import difflib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from generate_sources import get_token, api_get  # noqa: E402

SCRATCH = os.path.join(HERE, "scratch")
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SOURCES_LUA_PATH = os.path.join(REPO_ROOT, "Where2Go", "Core", "Sources.lua")
ITEM_STATS_LUA_PATH = os.path.join(REPO_ROOT, "Where2Go", "Core", "ItemStats.lua")

PRIMARY_STAT_TYPES = {"STRENGTH", "AGILITY", "INTELLECT"}
SECONDARY_STAT_TYPES = {"CRIT_RATING", "HASTE_RATING", "MASTERY_RATING", "VERSATILITY"}


def extract_item_ids(sources_lua_text):
    item_ids = set()
    for match in re.finditer(r"itemIds\s*=\s*\{([^}]*)\}", sources_lua_text):
        for piece in match.group(1).split(","):
            piece = piece.strip()
            if piece:
                item_ids.add(int(piece))
    return item_ids


def fetch_item_stats(token, item_id):
    data = api_get(token, f"/data/wow/item/{item_id}")
    preview = data.get("preview_item", {})
    stats = preview.get("stats", [])
    primary_stats = []
    secondary_stats = []
    for stat in stats:
        if stat.get("is_negated"):
            continue
        stat_type = stat.get("type", {}).get("type")
        if stat_type in PRIMARY_STAT_TYPES:
            primary_stats.append(stat_type)
        elif stat_type in SECONDARY_STAT_TYPES:
            secondary_stats.append(stat_type)
    return {"primaryStats": primary_stats, "secondaryStats": secondary_stats}


def render_lua(item_stats):
    lines = [
        "-- Regenerated by tools/data-prep/generate_item_stats.py from the Battle.net",
        "-- Game Data API. Do not hand-edit -- if the data needs correcting, regenerate",
        "-- from the same source. See docs/SEASON_CHECKLIST.md.",
        "",
        "Where2GoItemStats = {}",
        "",
        "Where2GoItemStats.STATS = {",
    ]
    for item_id in sorted(item_stats.keys()):
        stats = item_stats[item_id]
        primary = ", ".join(f'"{s}"' for s in stats["primaryStats"])
        secondary = ", ".join(f'"{s}"' for s in stats["secondaryStats"])
        lines.append(
            f"    [{item_id}] = {{ primaryStats = {{ {primary} }}, "
            f"secondaryStats = {{ {secondary} }} }},"
        )
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def diff_against_current(new_content):
    if os.path.exists(ITEM_STATS_LUA_PATH):
        with open(ITEM_STATS_LUA_PATH, "r", encoding="utf-8") as f:
            current_content = f.read()
    else:
        current_content = ""
    diff = difflib.unified_diff(
        current_content.splitlines(keepends=True),
        new_content.splitlines(keepends=True),
        fromfile="Where2Go/Core/ItemStats.lua (current)",
        tofile="scratch/ItemStats.lua.new (generated)",
    )
    diff_text = "".join(diff)
    print(diff_text if diff_text else "No differences from the current ItemStats.lua.")
    return diff_text


def main():
    with open(SOURCES_LUA_PATH, "r", encoding="utf-8") as f:
        sources_text = f.read()
    item_ids = extract_item_ids(sources_text)

    token = get_token()
    item_stats = {}
    for item_id in sorted(item_ids):
        item_stats[item_id] = fetch_item_stats(token, item_id)

    new_content = render_lua(item_stats)

    os.makedirs(SCRATCH, exist_ok=True)
    staged_path = os.path.join(SCRATCH, "ItemStats.lua.new")
    with open(staged_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Staged output written to {staged_path}, {len(item_ids)} items fetched")

    diff_against_current(new_content)


if __name__ == "__main__":
    main()
