"""Regenerate Where2Go/Core/Sources.lua's dungeon/raid item-pool data from
the Battle.net Game Data API Journal endpoints for the current season.

Usage (PowerShell):
    $env:BLIZZARD_CLIENT_ID="<your id>"; $env:BLIZZARD_CLIENT_SECRET="<your secret>"; python tools/data-prep/generate_sources.py

Never writes Where2Go/Core/Sources.lua directly -- it stages output at
tools/data-prep/scratch/Sources.lua.new and prints a diff for review.
See docs/SEASON_CHECKLIST.md for the full season-changeover procedure.
"""

import base64
import difflib
import json
import os
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
SCRATCH = os.path.join(HERE, "scratch")
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SOURCES_LUA_PATH = os.path.join(REPO_ROOT, "Where2Go", "Core", "Sources.lua")

REGION_HOST = "https://us.api.blizzard.com"

# Update this each season -- see docs/SEASON_CHECKLIST.md step 1. The
# Battle.net API has no "current season" endpoint, so these instance IDs
# must be looked up by hand (e.g. wowhead/wiki) and filled in here.
SEASON_INSTANCES = {
    "dungeons": [1322, 1311, 1304, 1309, 1313, 1041, 1202, 1030],
    "raids": [1317, 1320],
}

# Plain-text label for the generated Lua header. Keep this in sync with
# Where2GoConstants.SEASON_LABEL in Where2Go/Core/Constants.lua -- it isn't
# fetched from that file automatically, so update both by hand each season
# (see docs/SEASON_CHECKLIST.md).
SEASON_LABEL = "Season 2 (Midnight patch 12.1)"


def get_token():
    client_id = os.environ["BLIZZARD_CLIENT_ID"]
    client_secret = os.environ["BLIZZARD_CLIENT_SECRET"]
    auth = base64.b64encode(f"{client_id}:{client_secret}".encode()).decode()
    req = urllib.request.Request(
        "https://oauth.battle.net/token",
        data=b"grant_type=client_credentials",
        headers={"Authorization": f"Basic {auth}"},
        method="POST",
    )
    with urllib.request.urlopen(req) as resp:
        data = json.load(resp)
    os.makedirs(SCRATCH, exist_ok=True)
    with open(os.path.join(SCRATCH, "token.json"), "w", encoding="utf-8") as f:
        json.dump(data, f)
    return data["access_token"]


def api_get(token, path, namespace="static-us", locale="en_US"):
    url = f"{REGION_HOST}{path}?namespace={namespace}&locale={locale}"
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}"})
    with urllib.request.urlopen(req) as resp:
        return json.load(resp)


def fetch_instance(token, instance_id):
    instance = api_get(token, f"/data/wow/journal-instance/{instance_id}")
    os.makedirs(SCRATCH, exist_ok=True)
    with open(
        os.path.join(SCRATCH, f"raw_instance_{instance_id}.json"), "w", encoding="utf-8"
    ) as f:
        json.dump(instance, f)
    encounters = []
    for enc_ref in instance.get("encounters", []):
        enc_id = enc_ref["id"]
        detail = api_get(token, f"/data/wow/journal-encounter/{enc_id}")
        os.makedirs(SCRATCH, exist_ok=True)
        with open(
            os.path.join(SCRATCH, f"raw_encounter_{enc_id}.json"), "w", encoding="utf-8"
        ) as f:
            json.dump(detail, f)
        item_ids = [item["item"]["id"] for item in detail.get("items", [])]
        encounters.append({
            "bossId": enc_id,
            "name": detail["name"],
            "itemIds": item_ids,
        })
    return {"instanceId": instance_id, "name": instance["name"], "encounters": encounters}


def check_structural_warnings(label, instances):
    for instance in instances:
        seen_boss_ids = set()
        for encounter in instance["encounters"]:
            if not encounter["itemIds"]:
                print(
                    f"WARNING: {label} '{instance['name']}' encounter "
                    f"'{encounter['name']}' (bossId {encounter['bossId']}) has no items"
                )
            if encounter["bossId"] in seen_boss_ids:
                print(
                    f"WARNING: {label} '{instance['name']}' has duplicate "
                    f"bossId {encounter['bossId']}"
                )
            seen_boss_ids.add(encounter["bossId"])


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_instance(instance):
    lines = ["    {"]
    lines.append(f"        instanceId = {instance['instanceId']},")
    lines.append(f"        name = {lua_str(instance['name'])},")
    lines.append("        encounters = {")
    for encounter in instance["encounters"]:
        item_ids_str = ", ".join(str(i) for i in encounter["itemIds"])
        lines.append(
            f"            {{ bossId = {encounter['bossId']}, "
            f"name = {lua_str(encounter['name'])}, "
            f"itemIds = {{ {item_ids_str} }} }},"
        )
    lines.append("        },")
    lines.append("    },")
    return "\n".join(lines)


def render_lua(dungeons, raids, season_label):
    lines = [
        "-- Regenerated by tools/data-prep/generate_sources.py from the Battle.net",
        f"-- Game Data API Journal endpoints for {season_label}. Do not hand-edit --",
        "-- if the data needs correcting, regenerate from the same source. See",
        "-- docs/SEASON_CHECKLIST.md.",
        "",
        "Where2GoSources = {}",
        "",
        "Where2GoSources.DUNGEONS = {",
    ]
    for instance in dungeons:
        lines.append(render_instance(instance))
    lines.append("}")
    lines.append("")
    lines.append("Where2GoSources.RAIDS = {")
    for instance in raids:
        lines.append(render_instance(instance))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def diff_against_current(new_content):
    if os.path.exists(SOURCES_LUA_PATH):
        with open(SOURCES_LUA_PATH, "r", encoding="utf-8") as f:
            current_content = f.read()
    else:
        current_content = ""
    diff = difflib.unified_diff(
        current_content.splitlines(keepends=True),
        new_content.splitlines(keepends=True),
        fromfile="Where2Go/Core/Sources.lua (current)",
        tofile="scratch/Sources.lua.new (generated)",
    )
    diff_text = "".join(diff)
    print(diff_text if diff_text else "No differences from the current Sources.lua.")
    return diff_text


def main():
    token = get_token()
    dungeons = [fetch_instance(token, iid) for iid in SEASON_INSTANCES["dungeons"]]
    raids = [fetch_instance(token, iid) for iid in SEASON_INSTANCES["raids"]]

    check_structural_warnings("DUNGEONS", dungeons)
    check_structural_warnings("RAIDS", raids)

    new_content = render_lua(dungeons, raids, SEASON_LABEL)

    os.makedirs(SCRATCH, exist_ok=True)
    staged_path = os.path.join(SCRATCH, "Sources.lua.new")
    with open(staged_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Staged output written to {staged_path}")

    diff_against_current(new_content)


if __name__ == "__main__":
    main()
