"""Generate addon-owned dungeon, raid, and boss display-name localization.

This reads the same Battle.net Game Data API Journal endpoints as
generate_sources.py, but fetches them in en_US and ko_KR so Locale.lua can
keep English source names as canonical keys while showing official Korean
display names in the UI.

Usage (PowerShell):
    $env:BLIZZARD_CLIENT_ID="<your id>"; $env:BLIZZARD_CLIENT_SECRET="<your secret>"; python tools/data-prep/generate_content_locale.py

Never writes Where2Go/Core/Locale.lua directly. It stages a replacement
Where2GoLocale.CONTENT_NAMES table at scratch/ContentNames.lua.new for review.
"""

import os

from generate_sources import SEASON_INSTANCES, api_get, get_token, lua_str


HERE = os.path.dirname(os.path.abspath(__file__))
SCRATCH = os.path.join(HERE, "scratch")

LOCALES = {"enUS": "en_US", "koKR": "ko_KR"}


def fetch_instance(token, instance_id, locale):
    instance = api_get(token, f"/data/wow/journal-instance/{instance_id}", locale=locale)
    encounters = []
    for enc_ref in instance.get("encounters", []):
        enc_id = enc_ref["id"]
        detail = api_get(token, f"/data/wow/journal-encounter/{enc_id}", locale=locale)
        encounters.append({
            "bossId": enc_id,
            "name": detail["name"],
            "itemIds": [item["item"]["id"] for item in detail.get("items", [])],
        })
    return {"instanceId": instance_id, "name": instance["name"], "encounters": encounters}


def fetch_season_content(token, locale):
    return {
        "dungeons": [fetch_instance(token, instance_id, locale) for instance_id in SEASON_INSTANCES["dungeons"]],
        "raids": [fetch_instance(token, instance_id, locale) for instance_id in SEASON_INSTANCES["raids"]],
    }


def index_instances(content):
    by_id = {}
    for kind in ("dungeons", "raids"):
        for instance in content[kind]:
            by_id[instance["instanceId"]] = instance
    return by_id


def index_encounters(instance):
    return {encounter["bossId"]: encounter for encounter in instance["encounters"]}


def add_mapping(mapping, canonical, localized, context):
    existing = mapping.get(canonical)
    if existing is not None and existing != localized:
        raise ValueError(
            f"Conflicting localized names for {canonical!r}: {existing!r} vs {localized!r} at {context}"
        )
    mapping[canonical] = localized


def build_content_name_mapping(canonical_content, localized_content):
    localized_instances = index_instances(localized_content)
    mapping = {}

    for kind in ("dungeons", "raids"):
        for canonical_instance in canonical_content[kind]:
            instance_id = canonical_instance["instanceId"]
            localized_instance = localized_instances.get(instance_id)
            if not localized_instance:
                raise ValueError(f"Localized content is missing instanceId {instance_id}")
            add_mapping(
                mapping,
                canonical_instance["name"],
                localized_instance["name"],
                f"instanceId {instance_id}",
            )

            localized_encounters = index_encounters(localized_instance)
            for canonical_encounter in canonical_instance["encounters"]:
                boss_id = canonical_encounter["bossId"]
                localized_encounter = localized_encounters.get(boss_id)
                if not localized_encounter:
                    raise ValueError(f"Localized content is missing bossId {boss_id}")
                add_mapping(
                    mapping,
                    canonical_encounter["name"],
                    localized_encounter["name"],
                    f"bossId {boss_id}",
                )

    return mapping


def render_lua_table(locale_mappings):
    lines = [
        "-- Regenerated by tools/data-prep/generate_content_locale.py from the",
        "-- Battle.net Game Data API Journal endpoints. Do not hand-edit this table;",
        "-- regenerate and review the staged table instead.",
        "Where2GoLocale.CONTENT_NAMES = {",
    ]
    for locale_key in ("enUS", "koKR"):
        lines.append(f"    {locale_key} = {{")
        mapping = locale_mappings[locale_key]
        for canonical in sorted(mapping):
            lines.append(f"        [{lua_str(canonical)}] = {lua_str(mapping[canonical])},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    token = get_token()
    canonical = fetch_season_content(token, LOCALES["enUS"])
    localized = {
        "enUS": canonical,
        "koKR": fetch_season_content(token, LOCALES["koKR"]),
    }
    locale_mappings = {
        "enUS": build_content_name_mapping(canonical, localized["enUS"]),
        "koKR": build_content_name_mapping(canonical, localized["koKR"]),
    }
    rendered = render_lua_table(locale_mappings)
    os.makedirs(SCRATCH, exist_ok=True)
    staged_path = os.path.join(SCRATCH, "ContentNames.lua.new")
    with open(staged_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(rendered)
    print(f"Staged output written to {staged_path}")


if __name__ == "__main__":
    main()
